CREATE TABLE public.aluno (
                              matricula int4 NOT NULL,
                              nome varchar(255) NOT NULL,
                              data_nascimento date NOT NULL,
                              idade int4 NOT NULL,
                              contato varchar(255) NULL,
                              sexo bpchar(1) NULL,
                              CONSTRAINT aluno_pkey PRIMARY KEY (matricula)
);

CREATE TABLE public.aula (
                             "data" date NOT NULL,
                             tema varchar(255) NOT NULL,
                             descricao varchar(255) NULL,
                             CONSTRAINT aula_pkey PRIMARY KEY (data)
);

CREATE TABLE public.alunos_aula (
                                    id varchar(255) NOT NULL,
                                    matricula int4 NOT NULL,
                                    id_aula date NOT NULL,
                                    presenca int4 NOT NULL,
                                    CONSTRAINT alunos_aula_pkey PRIMARY KEY (id)
);

ALTER TABLE public.alunos_aula ADD CONSTRAINT fk_aluno_aula FOREIGN KEY (matricula) REFERENCES public.aluno(matricula);
ALTER TABLE public.alunos_aula ADD CONSTRAINT fk_aula FOREIGN KEY (id_aula) REFERENCES public.aula("data");

CREATE TABLE public.mensalidade (
                                    id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                    quantidade_aula int4 NOT NULL,
                                    valor numeric NOT NULL,
                                    situacao bool NOT NULL,
                                    comprovante int4 NOT NULL,
                                    periodo varchar(3) NOT NULL,
                                    matricula_aluno int4 NOT NULL,
                                    tipo_pagamento varchar NOT NULL,
                                    ano varchar NOT NULL,
                                    CONSTRAINT mensalidade_pkey PRIMARY KEY (id)
);

ALTER TABLE public.mensalidade ADD CONSTRAINT fk_mensalidade_aluno FOREIGN KEY (matricula_aluno) REFERENCES public.aluno(matricula) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;